system:
    ezdemo_site_user:
        ezpage:
            layouts:
                MFZoneLayout:
                    name: "Mayflower Zone Layout"
                    template: MayflowerTemplateTutorialBundle:page/zonelayout:mfzonelayout.html.twig
            enabledLayouts: [MFZoneLayout]
            blocks:
                MFBlock:
                    name: "Mayflower Block"
            enabledBlocks: [MFBlock]
        location_view:
            full:
                landing_page:
                    template: MayflowerTemplateTutorialBundle:full:landing.html.twig
                    match:
                        Identifier\ContentType: landing_page
                article:
                    template: MayflowerTemplateTutorialBundle:full:article.html.twig
                    match:
                        Identifier\ContentType: article
            listitem:
                article:
                    template: MayflowerTemplateTutorialBundle:line:article.html.twig
                    match:
                        Identifier\ContentType: article