system:
    ezdemo_site_user:
        location_view:
            full:
                article:
                    template: MayflowerTemplateTutorialBundle:full:article.html.twig
                    match:
                        Identifier\ContentType: article