system:
    ezdemo_site_user:
        location_view:
            full:
                landing_page:
                    template: MayflowerTemplateTutorialBundle:full:landing.html.twig
                    match:
                        Identifier\ContentType: landing_page