parameters:
  mayflower_template_tutorial.subtree.class: Mayflower\TemplateTutorialBundle\Controller\SubtreeController

services:
  mayflower_template_tutorial.subtree:
    class: %mayflower_template_tutorial.subtree.class%
    arguments: [@ezpublish.view_manager]
    calls:
      - [setContainer, [@service_container]]
  subtree:
    alias: mayflower_template_tutorial.subtree
